const GET_MESSAGES = "GET_MESSAGES"
const ADD_MESSAGE = "ADD_MESSAGE"
const DELETE_MESSAGE = "DELETE_MESSAGE"
const EDIT_MESSAGE = "EDIT_MESSAGE"
const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const CLEAR_MESSAGES = "CLEAR_MESSAGES"
 
export {
  GET_MESSAGES,
  ADD_MESSAGE,
  EDIT_MESSAGE,
  DELETE_MESSAGE,
  SET_CURRENT_USER,
  CLEAR_CURRENT_USER,
  CLEAR_MESSAGES
}